using Microsoft.AspNetCore.Mvc.Rendering;

namespace EmployeeCrud_Sat.Models.ViewModels
{
    public class EditEmployeeDto
    {
        public int EmployeeId { get; set; }

        public string? EmployeeCode { get; set; } // Keep this readonly in UI if it's autogenerated

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public int CountryId { get; set; }
        public int StateId { get; set; }
        public int CityId { get; set; }

        public string? CountryName { get; set; }
        public string? StateName { get; set; }
        public string? CityName { get; set; }

        public string EmailAddress { get; set; }

        public string MobileNumber { get; set; }

        public string PanNumber { get; set; }

        public string PassportNumber { get; set; }

        public string? ProfileImage { get; set; }

        public byte Gender { get; set; } // Or use `byte` or enum if needed

        public string DateOfBirth { get; set; } // formatted as "yyyy-MM-dd"

        public string? DateOfJoinee { get; set; } // formatted as "yyyy-MM-dd"

      
        public IEnumerable<SelectListItem> Countries { get; set; }
        public IEnumerable<SelectListItem> States { get; set; }
        public IEnumerable<SelectListItem> Cities { get; set; }
    }
}
